/**
 * File-based session storage.
 * Sessions saved as JSON in ~/.eklavya/sessions/<id>.json
 * No native dependencies — works everywhere Node.js runs.
 */

import fs from 'fs';
import path from 'path';
import { Session } from './types.js';
import { getSessionsDir, ensureDirs } from './config.js';

export function saveSession(session: Session): string {
  ensureDirs();
  const dir = getSessionsDir();
  const file = path.join(dir, `${session.id}.json`);
  fs.writeFileSync(file, JSON.stringify(session, null, 2));
  return file;
}

export function loadSession(id: string): Session {
  const dir = getSessionsDir();
  const file = path.join(dir, `${id}.json`);

  if (!fs.existsSync(file)) {
    throw new Error(`Session not found: ${id}`);
  }

  return JSON.parse(fs.readFileSync(file, 'utf-8')) as Session;
}

export function listSessions(limit = 20): Session[] {
  ensureDirs();
  const dir = getSessionsDir();

  const files = fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      const full = path.join(dir, f);
      const stat = fs.statSync(full);
      return { file: full, mtime: stat.mtimeMs };
    })
    .sort((a, b) => b.mtime - a.mtime)
    .slice(0, limit);

  return files.map(f => JSON.parse(fs.readFileSync(f.file, 'utf-8')) as Session);
}

export function exportSessionMarkdown(session: Session): string {
  const lines: string[] = [
    `# Eklavya Council Session`,
    ``,
    `**Question:** ${session.question}`,
    `**Council:** ${session.council_name}`,
    `**Date:** ${new Date(session.created_at).toLocaleString()}`,
    `**Duration:** ${session.duration_seconds}s`,
    `**Personas:** ${session.persona_count} | **Rounds:** ${session.rounds}`,
    ``,
    `---`,
    ``,
    `## Transcript`,
    ``,
  ];

  let lastRound = -99;
  for (const msg of session.transcript) {
    if (msg.round !== lastRound) {
      if (msg.round === 0) {
        lines.push(`### Opening`);
      } else if (msg.round === -1) {
        lines.push(`### Synthesis`);
      } else {
        lines.push(`### Round ${msg.round}`);
      }
      lines.push('');
      lastRound = msg.round;
    }
    lines.push(`**${msg.speaker}** *(${msg.speaker_role})*`);
    lines.push('');
    lines.push(msg.content);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Synthesis');
  lines.push('');
  lines.push(`> ${session.synthesis.summary}`);
  lines.push('');

  if (session.synthesis.decisions.length > 0) {
    lines.push('### ✓ Decisions');
    session.synthesis.decisions.forEach((d, i) => lines.push(`${i + 1}. ${d}`));
    lines.push('');
  }

  if (session.synthesis.dissent.length > 0) {
    lines.push('### ⚡ Dissent');
    session.synthesis.dissent.forEach(d => lines.push(`- ${d}`));
    lines.push('');
  }

  if (session.synthesis.open_questions.length > 0) {
    lines.push('### ? Open Questions');
    session.synthesis.open_questions.forEach(q => lines.push(`- ${q}`));
    lines.push('');
  }

  if (session.synthesis.actions.length > 0) {
    lines.push('### → Actions');
    session.synthesis.actions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
    lines.push('');
  }

  lines.push(`*Confidence: ${session.synthesis.confidence.toUpperCase()}*`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [Eklavya Council](https://github.com/sreenathmmenon/eklavya-council)*');

  return lines.join('\n');
}
